services:
  mysql:
    image: mysql:8.0
    container_name: coupon-event-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon_event
      MYSQL_USER: coupon
      MYSQL_PASSWORD: coupon
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
