spring:
  application:
    name: coupon-event
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_event?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: coupon
    password: coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
