spring:
  application:
    name: coupon-event
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_event?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: coupon
    password: coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: coupon-issue-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      fetch-max-wait: 200ms
    listener:
      type: batch
      concurrency: 3
      ack-mode: manual
